male(joe).
male(jerry).
male(sam).
male(garry).
female(juily).
female(jen).
female(samira).
female(leeniz).
parent(joe,juily).
parent(joe,sam).
parent(jerry,garry).
parent(jerry,leeniz).
parent(juily,garry).
parent(juily,leeniz).
parent(sam,samira).
parent(jen,samira).
grandparent(X,Y):-parent(X,Z),parent(Z,Y).
grandfather(X,Y):-male(X),grandparent(X,Y).
grandmother(X,Y):-female(X),grandparent(X,Y).
father(X,Y):-male(X),parent(X,Y).
mother(X,Y):-female(X),parent(X,Y).
sibling(X,Y):-parent(Z,X),parent(Z,Y).
sister(X,Y):-female(X),sibling(X,Y).
brother(X,Y):-male(X),sibling(X,Y).
aunt(X,Y):-parent(Z,Y),sister(X,Z).
cousin(X,Y):-parent(A,X),parent(B,Y),sibling(A,B).
nephew(X,Y):-male(X),parent(Z,X),sibling(Y,Z).
niece(X,Y):-female(X),parent(Z,X),sibling(Y,Z).
ancestor(X,Y):-parent(X,Z),grandparent(Z,Y).
